### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by thomasdavis** [metaory/jsonresume-theme-meta#1]
I like the theme, is it possible to publish to npm so it can be used on the registry? 

The main script would have to export a method called `render`

**Comment by metaory** [comment]
@thomasdavis sorry for a year late reply!

closing this issue, and will archive this repo sometime soon,

While it's layout looks ok, its tech is not!
I've been hesitant to touch this since

---

I did couple other related projects since,

- yet another somewhat legacy theme, still handlebars, but on Vite with hot-reloads, and portable pdf export method, [jsonresume-theme-legacy](https://github.com/metaory/jsonresume-theme-legacy)

![screenshotz](https://github.com/user-attachments/assets/9c5d6986-8e41-42b8-965c-656e5692ef08)

---

- a fork that adds secret gist support [jsonresume-service](https://github.com/metaory/jsonresume-service)

---

I'm starting to do my most ideal minimal version with Astro soon
under this repo [jsonresume-theme-roundy](https://github.com/metaory/jsonresume-theme-roundy) sometime soon hopefully !
